variables:
- group: TF

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

container:
  image: ldvcm/azure-devops-tf-agent

steps:
- task: CmdLine@2
  inputs:
    script: 'terraform --version'
- task: CmdLine@2
  inputs:
    script: 'terraform init'
- task: CmdLine@2
  inputs:
    script: 'terraform workspace select prod'
- task: CmdLine@2
  inputs:
    script: 'terraform apply --var-file=prod.tfvars -auto-approve'